FROM mysql:9.3
# Копируем файлы конфигурации
COPY ./slave.cnf /etc/mysql/conf.d/my.cnf
COPY ./slave.sql /docker-entrypoint-initdb.d/start.sql
# Переменные окружения для настройки репликации
ENV MYSQL_ROOT_PASSWORD=12345
# Запускаем сервисы
CMD ["mysqld"]
